#!/bin/sh

if [ ! -z "$1" ] 
then
	BUILD_VERSION="$1"
else
	BUILD_VERSION="NOT_VERSIONED"
fi

BUILD_DATE=$(date -R)

echo "// DO NOT EDIT THIS FILE MANUALLY,"
echo "// it is generated automatically by util/gen-buildconf.sh"
echo "// during each build."
echo ""
echo "#define BUILD_DATE \"$BUILD_DATE\""
echo "#define BUILD_VERSION \"$BUILD_VERSION\""
